name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  luau-lsp:
    name: Luau LSP Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup aftman toolchain
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Install wally dependencies
        run: wally install
      - name: Generate Rojo Sourcemap
        run: rojo sourcemap --output sourcemap.json
    #   - name: Re-Export Wally Package Types
    #     run: wally-package-types --sourcemap sourcemap.json ./Packages
      - name: Download latest Roblox API types
        run: |
          curl \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O \
            -L 'https://api.github.com/repos/JohnnyMorganz/luau-lsp/contents/scripts/globalTypes.d.lua'
      - name: Verify type safety with luau-lsp
        run: lune run workflowtools/RunLuauLSP.luau
  selene:
    name: Selene
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup aftman toolchain
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Verify code integrity with selene 
        run: selene src
  stylua:
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.0.2
          args: --check ./src
  